from .auth import AuthDomainService
from .camera import CameraDomainService
from .cloud import CloudDomainService
from .message import MessageDomainService
from .pairing import PairingDomainService
from .playback import PlaybackDomainService
from .runtime import RuntimeDomainService
from .station import StationDomainService

DOMAIN_SERVICE_FACTORIES = {
    "auth_domain": AuthDomainService,
    "station_domain": StationDomainService,
    "camera_domain": CameraDomainService,
    "pairing_domain": PairingDomainService,
    "message_domain": MessageDomainService,
    "playback_domain": PlaybackDomainService,
    "cloud_domain": CloudDomainService,
    "runtime_domain": RuntimeDomainService,
}

DOMAIN_METHODS = {
    "auth_domain": (
        "ensure_default_user",
        "login",
        "login_payload_for_station",
        "client_credentials_payload",
        "refresh",
        "profile",
        "update_user_profile",
        "issue_verification_code",
        "verify_code",
        "register_email",
        "register_user",
        "reset_password",
        "change_password",
    ),
    "station_domain": (
        "bind_station_to_user",
        "unbind_station_from_user",
        "station_bindings_for_user",
        "station_bind_check_payload",
        "ensure_station_did",
        "backfill_station_dids",
        "upsert_station_did_mapping",
        "station_did_mapping_payload",
        "set_station",
        "station_exists",
        "update_station_status",
        "update_station_session",
        "update_station_attr",
        "station_bind_list",
    ),
    "camera_domain": (
        "camera_bind_check_payload",
        "ensure_camera",
        "mark_camera_bound",
        "remove_station",
        "remove_camera",
        "update_camera_settings",
        "camera_index_payload",
        "my_devices_payload",
        "station_camera_list_payload",
        "camera_status_payload",
    ),
    "pairing_domain": (
        "upsert_pairing_session",
        "pairing_session_list",
        "pairing_slot_list",
        "resolve_pairing_context",
        "reserve_pairing_slot",
        "activate_pairing_slot",
        "release_pairing_slot",
    ),
    "message_domain": (
        "add_notice",
        "refresh_messages_from_station_if_needed",
        "set_push_token",
        "push_registrations",
        "message_count_payload",
        "message_filter_payload",
        "message_list_payload",
        "remove_messages",
        "remove_messages_matching",
    ),
    "playback_domain": (
        "storage_video_days",
        "storage_video_list_payload",
        "remove_cloud_media",
    ),
    "cloud_domain": (
        "cloud_media_asset_paths",
        "register_cloud_media_capture",
        "storage_camera_management_payload",
        "storage_purchase_plan_payloads",
        "storage_purchase_plan_page_payload",
        "storage_renew_plan_page_payload",
        "storage_service_info_payload",
        "storage_camera_unbind_list_payload",
        "set_cloud_storage_bound",
        "create_storage_order",
        "finalize_storage_order",
        "storage_payment_page_payload",
        "storage_payment_status_payload",
    ),
    "runtime_domain": (
        "consume_flag",
        "add_request",
        "append_request_log",
        "add_event",
        "session_key_payload",
        "check_session_key_payload",
        "remember_station_access_token",
        "station_sn_for_access_token",
        "mark_station_pairing_lock",
        "station_pairing_gate_payload",
        "state_summary",
        "recent_events",
        "push_status_payload",
        "dump_state",
    ),
}

DOMAIN_HELPER_METHODS = {
    "auth_domain": (
        "_normalize_email",
        "_normalize_mobile",
        "_canonical_username",
        "_hash_password",
        "_password_md5",
        "_looks_like_md5",
        "_looks_like_test_verify_code",
        "_normalize_person_name",
        "_full_name",
        "_effective_nickname",
        "_should_refresh_nickname_from_names",
        "_verify_password",
        "_row_to_profile",
        "_row_to_auth_result",
        "_state_user_from_row",
        "_state_auth_from_row",
        "_find_user",
        "_find_auth_by_access_token",
        "_find_auth_by_refresh_token",
        "_latest_auth_for_user",
        "_issue_tokens",
        "_set_active_session_unlocked",
        "_latest_auth_payload",
    ),
    "station_domain": (
        "_build_station",
        "_station_tombstone_key",
        "_station_is_removed_unlocked",
        "_remember_removed_station_unlocked",
        "_forget_removed_station_unlocked",
        "_remove_station_from_state_unlocked",
        "_normalize_station_hardver",
        "_normalize_station_model",
        "_default_station_did_storage",
        "_station_did_mappings_unlocked",
        "_station_did_is_real_unlocked",
        "_station_did_mapping_for_station_unlocked",
        "_station_did_from_pool_row_unlocked",
        "_upsert_station_did_pool_entry_unlocked",
        "_assign_station_did_pool_entry_unlocked",
        "_release_station_did_pool_for_station_unlocked",
        "_apply_station_did_to_state_unlocked",
        "_seed_station_did_pool_unlocked",
        "_assign_station_did_from_pool_unlocked",
        "_fallback_station_did_for_station_unlocked",
        "_upsert_station_did_mapping_unlocked",
        "_station_did_from_state_unlocked",
        "_normalize_station_record",
        "_station_did_from_state",
        "station_did_payload",
        "station_did_for_index",
        "_issued_station_dids_unlocked",
        "_station_did_needs_issue_unlocked",
        "_generate_unique_station_did_unlocked",
        "_ensure_station_did_unlocked",
        "_resolve_user_for_station_binding_unlocked",
        "_upsert_station_binding_unlocked",
        "_bound_station_sns_for_user_unlocked",
    ),
    "camera_domain": (
        "_build_camera",
        "_normalize_camera_hardver",
        "_normalize_camera_record",
        "_camera_battery_low",
        "_camera_version_marker",
        "_camera_tombstone_key",
        "_camera_is_removed_unlocked",
        "_remember_removed_camera_unlocked",
        "_forget_removed_camera_unlocked",
    ),
    "message_domain": (
        "_message_key",
        "_message_station_sn_unlocked",
        "_message_visible_for_scope_unlocked",
        "_message_tombstone_key",
        "_message_tombstone_key_for_message",
        "_collect_recording_notices",
        "_notice_type_from_ext",
        "_cloud_trigger_type_for_app",
        "_normalize_notice_text",
        "_should_refresh_notice_title",
        "_notice_title",
        "_camera_is_offline",
        "_massage_notice_payload_unlocked",
        "_format_notice_device_time",
        "_parse_notice_add_timestamp_ms",
        "_remember_removed_messages_unlocked",
        "_classify_push_token",
        "_is_viable_push_token",
        "_filtered_messages",
        "_new_notice_id_unlocked",
        "_append_notice_unlocked",
        "_append_system_notice_unlocked",
        "_build_notice_message_unlocked",
        "_latest_message_for_camera_unlocked",
        "_normalize_message_record_unlocked",
        "_export_share_metadata_unlocked",
    ),
    "pairing_domain": (
        "_ensure_station_row_unlocked",
        "_pairing_slot_payload_from_row",
    ),
    "cloud_domain": (
        "_coerce_str_list",
        "_normalize_date_digits",
        "_stream_code",
        "_parse_stream_code",
        "_cloud_capture_datetime_unlocked",
        "_cloud_media_identity_unlocked",
        "_normalize_cloud_media_record_unlocked",
        "_find_cloud_media_unlocked",
        "_find_message_for_cloud_media_unlocked",
        "_default_recording_file_type",
        "_notice_add_payload_for_recording_unlocked",
        "_recording_notice_fields_unlocked",
        "_message_device_time",
        "_public_base_url",
        "_cloud_cover_url",
        "_thumbnail_url",
        "_thumbnail_fields",
        "_parse_state_datetime",
        "_format_state_datetime",
        "_storage_plan_id",
        "_storage_plan_catalog_unlocked",
        "_paginate_items",
        "_resolve_storage_plan_unlocked",
        "_default_storage_service_unlocked",
        "_normalize_storage_state_unlocked",
        "_storage_days_remaining",
        "_storage_success_url",
        "_datetime_to_epoch_ms_str",
        "_existing_path",
        "_cloud_media_root_unlocked",
        "_cloud_media_owned_paths_unlocked",
        "_remove_cloud_media_files_unlocked",
        "_cloud_media_decode_path_unlocked",
        "_infer_cloud_media_asset_paths_unlocked",
        "_cloud_media_version_token_unlocked",
        "_allowed_camera_sns_for_scope_unlocked",
        "_scoped_camera_items_unlocked",
        "_effective_cloud_bound_camera_sns_unlocked",
        "_cloud_storage_camera_info_payload_unlocked",
    ),
    "runtime_domain": (
        "_coerce_switch_value",
        "_trim_log_value",
        "_user_id_for_access_token_unlocked",
        "_normalize_station_pairing_locks",
    ),
}


def init_store_domains(store) -> None:
    for attr_name, service_cls in DOMAIN_SERVICE_FACTORIES.items():
        setattr(store, attr_name, service_cls(store))


def install_domain_delegates(store_cls) -> None:
    def make_delegate(domain_attr: str, method_name: str):
        def _delegate(self, *args, **kwargs):
            return getattr(getattr(self, domain_attr), method_name)(*args, **kwargs)

        _delegate.__name__ = method_name
        _delegate.__qualname__ = f"{store_cls.__name__}.{method_name}"
        return _delegate

    for method_groups in (DOMAIN_HELPER_METHODS, DOMAIN_METHODS):
        for domain_attr, methods in method_groups.items():
            for method_name in methods:
                setattr(store_cls, method_name, make_delegate(domain_attr, method_name))

__all__ = [
    "AuthDomainService",
    "CameraDomainService",
    "CloudDomainService",
    "DOMAIN_HELPER_METHODS",
    "DOMAIN_METHODS",
    "DOMAIN_SERVICE_FACTORIES",
    "MessageDomainService",
    "PairingDomainService",
    "PlaybackDomainService",
    "RuntimeDomainService",
    "StationDomainService",
    "init_store_domains",
    "install_domain_delegates",
]
